# Generated by Django 5.2 on 2025-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('guarantee', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('chip', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=50)),
                ('internal_storage', models.CharField(max_length=50)),
                ('ram_storage', models.CharField(max_length=50)),
                ('camera_quality', models.CharField(max_length=50)),
                ('battery_capacity', models.CharField(max_length=80)),
                ('farsi_menu', models.CharField(choices=[('D', 'Darad'), ('N', 'Nadarad')], max_length=10)),
            ],
        ),
    ]
