# Generated by Django 5.2 on 2025-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='farsi_menu',
            field=models.CharField(choices=[('N', 'Nadarad'), ('D', 'Darad')], max_length=10),
        ),
    ]
